### ISSUE TITLE
failure parsing cookies

### ISSUE THREAD

**Issue by willkg** [willkg/fillmore#73]
Tests fail with this error:

```
During handling of the above exception, another exception occurred:
  Traceback (most recent call last):
    File "/home/runner/work/fillmore/fillmore/.tox/py39-django42/lib/python3.9/site-packages/fillmore/scrubber.py", line 369, in __call__
      filtered_val = rule.scrub(val)
    File "/home/runner/work/fillmore/fillmore/.tox/py39-django42/lib/python3.9/site-packages/fillmore/scrubber.py", line 75, in _scrub_cookies
      name, val = cookie.split("=", 1)
  ValueError: not enough values to unpack (expected 2, got 1)
```

That repeats like 1,000 times. The scrubber should be set up such that if it fails, it doesn't trigger another Sentry event. It should log something and recover.

**Comment by willkg** [comment]
Looks like sentry-sdk changed. It now replaces the entire header with `[Filtered]`, but includes the individual scrubbed cookies in the request:

```python
{
    'url': 'http://localhost/broken',
    'query_string': '',
    'method': 'GET',
    'env': {
        'SERVER_NAME': 'localhost',
        'SERVER_PORT': '80'
    },
    'headers': {
        'Host': 'localhost',
        'Cookie': '[Filtered]'
    },
    'cookies': {
        'csrftoken': '[Scrubbed]',
        'sessionid': '[Scrubbed]',
        'foo': 'bar'
    }
}
```
The `[Filtered]` is coming from sentry-sdk. The `[Scrubbed]` is coming from Fillmore. (NB: I made sure Fillmore used a different term so we could distinguish.)

I'm going to adjust Fillmore accordingly.
